export default {
  PLATE: require("../assets/images/plate.png"),
  DISCOVER: require("../assets/images/discover1.png"),
  DELIVER: require("../assets/images/deliver.png"),
  FAVORITE: require("../assets/images/favorite.png"),
  FACEBOOK: require("../assets/images/facebook.png"),
  GOOGLE: require("../assets/images/google.png"),
  LOADING: require("../assets/images/Animation - 1722778932512.json"),
  BUKETI: require("../assets/images/bouquet.png"),
  KUTIJE: require("../assets/images/gift-box.png"),
  SAKSIJE: require("../assets/images/potted-plant.png"),
  RODJENDANI: require("../assets/images/balloons.png"),
  BILJKE: require("../assets/images/aloe-vera.png"),
  VJENCANJA: require("../assets/images/hall.png"),
  DELIVERY_TIME: require("../assets/images/delivery_time.png"),
  DELIVERY_CHARGE: require("../assets/images/delivery_charge.png"),
  MARKER: require("../assets/images/marker.png"),
  EMPTY: require("../assets/images/space.png"),
  EMPTY_CART: require("../assets/images/empty_cart.png"),
  BACKGROUND: require("../assets/images/background3.png"),
  HUMANITY: require("../assets/images/humanity.png"),
  LOGO: require("../assets/images/logo.png"),
  AVATAR: require("../assets/images/user.png"),
  ACCOUNT: require("../assets/images/account.png"),
};
